name: Awaken Sleeping App
on:
  schedule:
    - cron: '15,30,45 6 * * *'
jobs:
  build:
    name: GET Request to API
    runs-on: ubuntu-latest
    steps:
      - name: Curl request
        run: curl https://ski-pass-snow-compare-api.herokuapp.com/api
